### ISSUE TITLE
Test with multiple versions of Python

### ISSUE THREAD

**Issue by uri-granta** [secondmind-labs/trieste#476]
We should consider have some tests run with multiple versions of Python (and possibly Tensorflow too), to catch bugs like https://github.com/secondmind-labs/trieste/issues/473.

Pros:
- catch backwards compatibility issues

Cons:
- more infrastructure
- more time to run tests (even if we only run them at release time)

**Comment by apaleyes** [comment]
Is it that much work? Say, to verify new version of Python all that's needed is few more lines in the action yaml:
```
  tests-3.8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install tox
    - run: tox -e tests
```

If we add this to develop checks, it won't even make the build longer, because the `alltests` action will take longer that this one, and they'll very likely start simultaneously. Happy to turn this into quick PR if you agree!
